/**
 * @behavior Reviewers can view, edit, approve, and reject AI-generated content
 * @user-story US-013: Content Review & Management
 * @boundary API (/api/v1/content)
 *
 * These acceptance tests verify the content review state machine:
 * draft → in_review → approved → published (or rejected).
 * Tests at the HTTP boundary.
 */
import { describe, it, expect } from 'vitest';

describe('Content Review (Acceptance)', () => {
  describe('Scenario: View Content Library (AC-013.1)', () => {
    it('should list all content filterable by status and type', async () => {
      // GIVEN - A project has generated content in various states

      // WHEN - I fetch content filtered by status
      const response = await fetch('/api/v1/content?status=in_review&limit=20', {
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - I see content items matching the filter
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data).toBeInstanceOf(Array);
      body.data.forEach((item: Record<string, unknown>) => {
        expect(item.status).toBe('in_review');
      });
    });

    it('should filter content by content_type', async () => {
      // GIVEN - Content exists with different types

      // WHEN - I filter by article type
      const response = await fetch('/api/v1/content?content_type=article', {
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - Only articles are returned
      expect(response.status).toBe(200);
      const body = await response.json();
      body.data.forEach((item: Record<string, unknown>) => {
        expect(item.content_type).toBe('article');
      });
    });
  });

  describe('Scenario: Review Content Detail (AC-013.2)', () => {
    it('should return full content with pipeline source info', async () => {
      // GIVEN - Content has been generated by a pipeline
      const contentId = 'content-uuid';

      // WHEN - I open the content detail
      const response = await fetch(`/api/v1/content/${contentId}`, {
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - I see the full article with metadata
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data).toMatchObject({
        id: contentId,
        title: expect.any(String),
        body: expect.anything(), // jsonb rich text
        meta_description: expect.any(String),
        tags: expect.any(Array),
        status: expect.any(String),
        content_type: expect.any(String),
      });
    });
  });

  describe('Scenario: Edit Before Approve (AC-013.3)', () => {
    it('should save edits to content fields', async () => {
      // GIVEN - I am reviewing content
      const contentId = 'content-to-edit';

      // WHEN - I make edits to the title and body
      const response = await fetch(`/api/v1/content/${contentId}`, {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          title: 'Edited Title: Better SEO',
          meta_description: 'Updated meta description for better CTR',
        }),
      });

      // THEN - The changes are saved
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data.title).toBe('Edited Title: Better SEO');
      expect(body.data.meta_description).toBe('Updated meta description for better CTR');
    });
  });

  describe('Scenario: Approve Content (AC-013.4)', () => {
    it('should change status to approved', async () => {
      // GIVEN - Content is in_review
      const contentId = 'content-to-approve';

      // WHEN - I click Approve
      const response = await fetch(`/api/v1/content/${contentId}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - Status changes to approved
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data.status).toBe('approved');
    });
  });

  describe('Scenario: Reject Content (AC-013.5)', () => {
    it('should change status to rejected with reason', async () => {
      // GIVEN - Content is in_review
      const contentId = 'content-to-reject';

      // WHEN - I click Reject with a reason
      const response = await fetch(`/api/v1/content/${contentId}/reject`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ reason: 'Tone does not match brand voice' }),
      });

      // THEN - Status changes to rejected
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data.status).toBe('rejected');
    });

    it('should not publish rejected content', async () => {
      // GIVEN - Content has been rejected
      const contentId = 'rejected-content';

      // WHEN - I check the content
      const response = await fetch(`/api/v1/content/${contentId}`, {
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - It has no published_url
      const body = await response.json();
      expect(body.data.status).toBe('rejected');
      expect(body.data.published_url).toBeNull();
    });
  });

  describe('Scenario: Bulk Approve (AC-013.6)', () => {
    it('should approve multiple content items at once', async () => {
      // GIVEN - Multiple content items are in_review
      const contentIds = ['content-1', 'content-2', 'content-3'];

      // WHEN - I bulk approve them
      const response = await fetch('/api/v1/content/bulk', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'approve',
          ids: contentIds,
        }),
      });

      // THEN - All items are approved
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data.updated).toBe(3);
      expect(body.data.status).toBe('approved');
    });
  });

  describe('Scenario: Bulk Reject (AC-013.6)', () => {
    it('should reject multiple content items at once', async () => {
      // GIVEN - Multiple content items are in_review
      const contentIds = ['content-4', 'content-5'];

      // WHEN - I bulk reject them
      const response = await fetch('/api/v1/content/bulk', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          action: 'reject',
          ids: contentIds,
          reason: 'Batch rejected — needs rewrite',
        }),
      });

      // THEN - All items are rejected
      expect(response.status).toBe(200);
      const body = await response.json();
      expect(body.data.updated).toBe(2);
      expect(body.data.status).toBe('rejected');
    });
  });

  describe('Scenario: Content State Machine Guards', () => {
    it('should not allow approving already published content', async () => {
      // GIVEN - Content is already published
      const contentId = 'published-content';

      // WHEN - I try to approve it again
      const response = await fetch(`/api/v1/content/${contentId}/approve`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
      });

      // THEN - I get an error
      expect(response.status).toBe(422);
      const body = await response.json();
      expect(body.error.code).toBe('INVALID_STATE_TRANSITION');
    });
  });
});
