// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgizzmbashsndqeunnwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnaXp6bWJhc2hzbmRxZXVubnd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3MTMzNDUsImV4cCI6MjA1NzI4OTM0NX0.qStnBYxJnYLSXaKKvckBJJyKlTMWcd-yIxtiq5eB5Ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);